=== z17/java-home-work/src/main/java/javase13/t01/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://test.ru/library">
  <xs:element name="library" type="libraryType"/>
  <xs:complexType name="libraryType">
    <xs:sequence>
      <xs:element type="categoriesType" name="categories"/>
      <xs:element type="booksType" name="books"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="categoriesType">
    <xs:sequence>
      <xs:element type="categoryType" name="category" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="categoryType">
    <xs:sequence>
      <xs:element name="id" type="xs:int"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="description" minOccurs="0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="booksType">
    <xs:sequence>
      <xs:element type="bookType" name="book" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="bookType">
    <xs:sequence>
      <xs:element name="id" type="xs:int"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="author" type="xs:string"/>
      <xs:element type="xs:string" name="language">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ru"/>
            <xs:enumeration value="en"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="reads" type="xs:int"/>
    </xs:sequence>
    <xs:attribute name="category" type="xs:int" use="required" />
  </xs:complexType>
</xs:schema>

=== z17/java-home-work/src/main/java/javase13/t01/library.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<library
        xmlns="http://test.ru/library"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://test.ru/library library.xsd">
    <categories>
        <category>
            <id>1</id>
            <name>История</name>
            <description>Учебники, книги по истории</description>
        </category>
        <category>
            <id>2</id>
            <name>Романы</name>
        </category>
        <category>
            <id>3</id>
            <name>Программирование</name>
        </category>
    </categories>
    <books>
        <book category="1">
            <id>1</id>
            <name>Учебник по Истории России 10 класс</name>
            <author>Сахаров</author>
            <language>ru</language>
            <reads>0</reads>
        </book>
        <book category="2">
            <id>2</id>
            <name>Черный обелиск</name>
            <author>Эрих Мария Ремарк</author>
            <language>ru</language>
            <reads>2</reads>
        </book>
        <book category="3">
            <id>3</id>
            <name>Совершенный код</name>
            <author>С. Макконнелл</author>
            <language>ru</language>
            <reads>1</reads>
        </book>
    </books>
</library>
